### PR TITLE
This configuration file is entirely broken for me with double quotes …

### PR DESCRIPTION
**Pull request by nakaomote**
…around values

So may as well bring this up for discussion.

### CODE REVIEW

**Comment by priestjim** [comment]
How do you mean broken?

**Comment by nakaomote** [comment]
Just tried this again with the latest version of this cookbook and it won't work until I take away the " characters.

**Comment by priestjim** [comment]
You mean Rundeck fails? Chef fails? What is the exact issue you're facing?

**Comment by nakaomote** [comment]
Actually nevermind. After a lot of experimenting I found out I was reading the log files incorrectly. Sorry I wasted your time on this. Everything is working for me. Sorry I just haven't been able to look at this for months.

**Pull request closed without merging**
